### ISSUE TITLE
十分小巧的Win端录音机，很棒！能否增加一些功能呢？

### ISSUE THREAD

**Issue by Caivin2015** [koala999cn/kRecorder#1]
如题，能否增加一个录音格式质量可筛选？诸如M4A（HE-AAC编码）、opus、amr等开源音频格式。可参考github上Dimowner大佬开发的AudioRecorder。
另外，能否增加一个随Windows启动并直接隐私录音（转换为Windows服务直接后台运行）功能开关？

**Comment by koala999cn** [comment]
已发行v0.2版：增加录音格式和质量选项，支持ogg，opus，flac和wav四种音频格式。暂无扩展支持m4a和amr的计划。
另外，增加了命令行选项以支持隐私录音，具体可参考readme文件
